name: flutter_instagram_app
description: "A production-grade Flutter Instagram clone demonstrating modern Flutter development practices, clean architecture, and comprehensive documentation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1
  google_fonts: ^6.1.0

  # Backend & Authentication
  supabase_flutter: ^2.0.0

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^12.1.3

  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  # image_cropper: ^5.0.1
  photo_view: ^0.14.0

  # Storage & Persistence
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network & HTTP
  dio: ^5.3.2
  connectivity_plus: ^5.0.1

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0

  # Media & Camera
  camera: ^0.10.5+5
  video_player: ^2.8.1
  chewie: ^1.7.4

  # Utilities
  timeago: ^3.6.0
  uuid: ^4.1.0
  path: ^1.8.3
  mime: ^1.0.4
  url_launcher: ^6.2.1
  share_plus: ^7.2.1

  # Environment & Configuration
  flutter_dotenv: ^5.1.0

  # Permissions
  permission_handler: ^11.0.1

  # Analytics & Monitoring
  # firebase_core: ^2.24.2
  # firebase_analytics: ^10.7.4
  # firebase_crashlytics: ^3.4.8

  # Internationalization
  intl: ^0.19.0

  # Animations
  lottie: ^2.7.0
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  patrol: ^3.19.0

  # Development Tools
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

  # Fonts
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  color_dark: "#000000"
  image_dark: assets/images/splash_logo_dark.png
  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash_logo_dark.png
    icon_background_color_dark: "#000000"
  web: false
